services:
  - type: web
    name: waste-classifier-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:10000
    plan: free