services:
  - type: web
    name: waste-classifier-api
    runtime: python
    plan: free
    region: singapore
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python -m gunicorn app:app --bind 0.0.0.0:10000"